/** Generated artifacts. build() is the only normal writer to <vault>/_gen. */
import { mkdirSync } from 'node:fs';
import * as path from 'node:path';
import { collectCapabilities } from './code.mjs';
import { readTextOrNull, sortBy, writeGeneratedText } from './fs.mjs';
import { buildGraph, resolveNoteReference } from './graph.mjs';
import { loadNotes } from './notes.mjs';

export async function buildContext(root, config) {
  const notes = loadNotes(root, config);
  const graph = buildGraph(notes, config);
  const facts = await collectCapabilities(root, config);
  return { root, config, notes, graph, ...facts };
}

function roadmapSummary(notes, config) {
  const resolved = resolveNoteReference(notes, config.roadmapNote, config.locale);
  if (!resolved?.note) return null;
  let done = 0;
  let open = 0;
  for (const line of resolved.note.lines) {
    const checkbox = line.match(/^\s*-\s*\[([ xX])\]/);
    if (checkbox) checkbox[1].toLowerCase() === 'x' ? done++ : open++;
  }
  return { note: resolved.note, done, open };
}

export function renderContext(ctx) {
  const { config, notes, graph, sourceFacts = [], codeMap = [], capabilities = {} } = ctx;
  const cmd = config.engineCommand;
  const lines = [
    `# vault context v1  notes=${notes.length} links=${graph.edges.length}`,
    '# Generated by the portable vault engine. Do not edit; rebuild with `build`.',
    '',
    '## ROUTES',
    `index    ${config.indexNote}`,
    `roadmap  ${config.roadmapNote}`,
    `context  ${config.vaultDir}/${config.contextDir}/ (background only; excluded from graph and search)`,
  ];
  if (config.currentContext)
    lines.push(
      `handoff  ${config.vaultDir}/${config.currentContext} (read separately; excluded from graph and search)`,
    );
  if (config.stack.length) lines.push('', '## STACK', ...config.stack);
  const roadmap = roadmapSummary(notes, config);
  lines.push('', `## STATUS${roadmap ? ` (canon ${roadmap.note.rel})` : ''}`);
  lines.push(
    roadmap
      ? `checkboxes  done=${roadmap.done} open=${roadmap.open}`
      : `roadmap note '${config.roadmapNote}' is not present yet`,
  );
  if (capabilities.sourceFacts && sourceFacts.length) {
    lines.push('', '## SOURCE FACTS (adapter-supplied)');
    for (const section of sourceFacts)
      lines.push(`${section.title}    ${section.rows.length} row(s)`);
    lines.push(
      `facts       ${config.vaultDir}/_gen/facts.txt (read only; generated from adapter capabilities)`,
    );
  }
  if (capabilities.codeMap && codeMap.length)
    lines.push(`map         ${config.vaultDir}/_gen/code-map.txt (adapter-supplied edit map)`);
  if (config.qualityCommands.length)
    lines.push('', '## QUALITY COMMANDS', ...config.qualityCommands.map((item) => item.command));
  lines.push(
    '',
    '## RETRIEVAL',
    `L2  ${cmd} find <query>  -> ranked note or section references`,
    `L3  ${cmd} show <ref>    -> one note section`,
    `    refs accept ${config.exampleRef}`,
    'L4  Read a focused source file only when implementation evidence is needed',
    `    ${cmd} map            -> generated curated-note map`,
  );
  if (graph.dangling.length) lines.push(`WARN dangling curated links: ${graph.dangling.length}`);
  if (graph.ambiguous.length) lines.push(`WARN ambiguous curated links: ${graph.ambiguous.length}`);
  if (!graph.index) lines.push(`WARN configured index '${config.indexNote}' does not resolve`);
  return lines.join('\n');
}

export function renderMap(ctx) {
  const rows = ['# path\ttitle\ttype\tsummary'];
  for (const note of sortBy(ctx.notes, (item) => item.rel)) {
    const clean = (value) =>
      String(value || '')
        .replace(/[\t\r\n]+/g, ' ')
        .trim();
    rows.push(
      `${note.rel}\t${clean(note.title)}\t${clean(note.type)}\t${clean(note.data.summary)}`,
    );
  }
  return rows.join('\n');
}

export function renderIndex(ctx) {
  return JSON.stringify(
    {
      version: 1,
      indexNote: ctx.graph.index,
      contextExcluded: `${ctx.config.vaultDir}/${ctx.config.contextDir}`,
      notes: sortBy(ctx.notes, (note) => note.rel).map((note) => ({
        rel: note.rel,
        path: note.path,
        name: note.name,
        title: note.title,
        type: note.type,
        summary: note.data.summary || null,
        rev: note.data.rev || null,
        headings: note.headings
          .filter((heading) => heading.level >= 2)
          .map((heading, index) => ({
            n: index + 1,
            level: heading.level,
            text: heading.text,
            line: heading.line,
            endLine: heading.endLine,
          })),
      })),
    },
    null,
    2,
  );
}

export function renderGraph(ctx) {
  const { graph, notes } = ctx;
  return JSON.stringify(
    {
      version: 1,
      metrics: {
        notes: notes.length,
        links: graph.edges.length,
        dangling: graph.dangling.length,
        ambiguous: graph.ambiguous.length,
        caseMismatch: graph.caseMismatch.length,
        components: graph.components.length,
        orphans: graph.orphans.length,
        unreachableFromIndex: graph.unreachable.length,
      },
      ...graph,
    },
    null,
    2,
  );
}

export function renderCodeMap(ctx) {
  const rows = ctx.codeMap || [];
  const lines = [
    `# code-map v1  files=${rows.length} symbols=${rows.reduce((total, row) => total + row.symbols.length, 0)}`,
    '# Generated by the selected optional adapter. Do not edit.',
  ];
  if (!rows.length)
    return lines
      .concat('# No code map: the selected adapter does not advertise codeMap.')
      .join('\n');
  let scope = null;
  let dir = null;
  for (const row of sortBy(
    rows,
    (item) => `${item.scope}\0${item.dir}\0${item.base || item.file}`,
  )) {
    if (row.scope !== scope || row.dir !== dir) {
      scope = row.scope;
      dir = row.dir;
      lines.push('', `## ${[scope, dir].filter(Boolean).join('/') || 'code'}`);
    }
    const symbols = row.symbols.map((symbol) => `${symbol.kind} ${symbol.name}`).join(', ');
    lines.push(`${row.base || row.file}\t${symbols || '-'}`);
  }
  return lines.join('\n');
}

export function renderFacts(ctx) {
  const lines = [
    '# vault source facts v1',
    '# Generated by an optional adapter. Do not edit; rebuild with `build`.',
    `adapter=${ctx.config.adapter}`,
  ];
  const sections = ctx.sourceFacts || [];
  if (!sections.length)
    return lines
      .concat('', '# No source facts: the selected adapter does not advertise sourceFacts.')
      .join('\n');
  for (const section of sections) lines.push('', `## ${section.title}`, ...section.rows);
  return lines.join('\n');
}

export function renderHealth(ctx) {
  const { graph } = ctx;
  const lines = [
    '# vault graph health — generated, do not edit',
    '# For frontmatter, graph, retrieval, and freshness findings run `check`.',
    `notes=${ctx.notes.length} links=${graph.edges.length} components=${graph.components.length}`,
    `dangling=${graph.dangling.length} ambiguous=${graph.ambiguous.length} case_mismatch=${graph.caseMismatch.length}`,
    `orphans=${graph.orphans.length} unreachable=${graph.unreachable.length}`,
  ];
  const sections = [
    ['DANGLING', graph.dangling.map((item) => `${item.from}:${item.line}\t[[${item.target}]]`)],
    [
      'AMBIGUOUS',
      graph.ambiguous.map(
        (item) => `${item.from}:${item.line}\t[[${item.target}]] -> ${item.candidates.join(' | ')}`,
      ),
    ],
    [
      'CASE MISMATCH',
      graph.caseMismatch.map(
        (item) => `${item.from}:${item.line}\t${item.target} -> ${item.actual}`,
      ),
    ],
    ['UNREACHABLE', graph.unreachable],
  ];
  for (const [title, entries] of sections)
    if (entries.length) lines.push('', `## ${title}`, ...entries);
  return lines.join('\n');
}

export const GEN_RENDERERS = Object.freeze({
  'context.txt': renderContext,
  'map.tsv': renderMap,
  'index.json': renderIndex,
  'graph.json': renderGraph,
  'code-map.txt': renderCodeMap,
  'facts.txt': renderFacts,
  'health.txt': renderHealth,
});

export function renderGenerated(ctx) {
  return Object.fromEntries(
    Object.entries(GEN_RENDERERS).map(([name, renderer]) => [name, renderer(ctx)]),
  );
}

/** The core's only normal writer; all target output stays in `_gen`. */
export async function build(root, config) {
  const ctx = await buildContext(root, config);
  const outputDirectory = path.resolve(root, config.vaultDir, '_gen');
  mkdirSync(outputDirectory, { recursive: true });
  const changed = [];
  for (const [name, content] of Object.entries(renderGenerated(ctx))) {
    const output = path.resolve(outputDirectory, name);
    if (writeGeneratedText(output, content)) changed.push(`${config.vaultDir}/_gen/${name}`);
  }
  process.stdout.write(
    changed.length
      ? `vault build: updated ${changed.length}\n${sortBy(changed).join('\n')}\n`
      : 'vault build: up to date\n',
  );
  return 0;
}

export function generatedFile(root, config, name) {
  return readTextOrNull(path.resolve(root, config.vaultDir, '_gen', name));
}
