/**
 * Generation of _gen/* and auto-block filling. WRITES — never callable from a hook.
 *
 * Determinism rules (violating any of these makes `check` flap):
 *   - no wall clock, no HEAD stamp, nothing volatile embedded
 *   - every collection sorted on raw code units, never localeCompare
 *   - LF / UTF-8 / no BOM / one trailing newline
 *
 * Language policy: section keys and derived facts are compact English (Cyrillic
 * tokenizes at ~2.5-3.5 tok/word vs ~1.3), but note titles, headings and
 * summaries stay VERBATIM Ukrainian — they are addresses that get passed to
 * Read/find, and a translated address cannot be resolved.
 */
import * as path from 'node:path';
import { mkdirSync } from 'node:fs';
import { CONFIG } from './config.mjs';
import {
  VAULT_DIR, GEN_DIR, BACKEND_DIR, CODE_PREFIX, readText, readTextOrNull, writeText, exists,
  cmp, sortBy, expandPatterns, resolveCodePattern, digestFiles, norm,
} from './fs.mjs';
import { loadNotes, parseNote, sectionOf } from './notes.mjs';
import { buildGraph } from './graph.mjs';
import { entities, migrations, providers, envVars, npmScripts, testCounts, codeMap } from './code.mjs';
import { parse as fmParse, serialize as fmSerialize } from './frontmatter.mjs';
import { collectFindings } from './rules.mjs';
import { git, stagedPaths } from './git.mjs';

/** Which package scripts are worth an agent's attention, in the order shown. */
const AGENT_SCRIPTS = CONFIG.agentScripts;

/** Everything the generators need, assembled once. */
export function buildContext(root) {
  const notes = loadNotes(root);
  const graph = buildGraph(notes);
  return {
    root,
    notes,
    graph,
    entities: entities(root),
    migrations: migrations(root),
    providers: providers(root),
    env: envVars(root),
    scripts: npmScripts(root),
    tests: testCounts(root),
    codeMap: codeMap(root),
  };
}

// ------------------------------------------------------------- context.txt

function roadmapSteps(notes) {
  const roadmap = notes.find((n) => n.name === 'Roadmap & Status');
  if (!roadmap) return { done: [], next: [], todo: [], extra: [] };
  const done = [], next = [], todo = [], extra = [];
  let inExtra = false;
  for (const raw of roadmap.lines) {
    const line = raw.replace(/\s+$/, '');
    if (/^##\s/.test(line)) inExtra = /Додатково/.test(line);
    const m = line.match(/^\s*-\s*\[([ xX])\]\s*(.+)$/);
    if (!m) continue;
    // Prefer the bolded step title. Roadmap bullets wrap across lines, so
    // taking the whole first line truncates mid-sentence; the **...** span is
    // the actual label. Kept verbatim Ukrainian — it is an address.
    const bold = m[2].match(/\*\*(.+?)\*\*/);
    const label = (bold ? bold[1] : m[2])
      .replace(/\*\*/g, '')
      .replace(/!?\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|([^\]]*))?\]\]/g, (_, t, a) => a || t)
      .replace(/→.*$/, '')
      .replace(/[—-]\s*$/, '')
      .replace(/\s+/g, ' ')
      .trim();
    const checked = m[1].toLowerCase() === 'x';
    if (inExtra) { if (checked) extra.push(label); continue; }
    if (checked) done.push(label);
    else if (/←\s*\**наступне|наступне/.test(m[2])) next.push(label);
    else todo.push(label);
  }
  return { done, next, todo, extra };
}

function invariantLines(notes) {
  const inv = notes.find((n) => n.name === 'Invariants');
  if (!inv) return [];
  // Verbatim Ukrainian H2 text — these are canonical addresses, not prose.
  return inv.headings.filter((h) => h.level === 2).map((h) => h.text.replace(/\s+/g, ' ').trim());
}

function dodSection(notes) {
  const roadmap = notes.find((n) => n.name === 'Roadmap & Status');
  if (!roadmap) return [];
  const idx = roadmap.headings.findIndex((h) => h.level === 2 && /Definition of Done/i.test(h.text));
  if (idx === -1) return [];
  const sec = sectionOf(roadmap, idx);
  return sec.text.split('\n').slice(1).map((l) => l.replace(/\s+$/, '')).filter(Boolean);
}

function testSummary(tests) {
  const fmt = (side) => {
    const by = sortBy(Object.entries(side.byDir || {}), ([k]) => k)
      .filter(([, v]) => v > 0)
      .map(([k, v]) => `${k === '(root)' ? 'app' : k}${v}`)
      .join(' ');
    const n = tests.hasEach ? `>=${side.cases}` : `${side.cases}`;
    return `${n}/${side.files}f${by ? ` [${by}]` : ''}`;
  };
  return { unit: fmt(tests.unit), int: fmt(tests.int) };
}

export function renderContext(ctx) {
  const { notes, graph, tests, env } = ctx;
  const steps = roadmapSteps(notes);
  const t = testSummary(tests);
  const L = [];

  L.push(`# ctx v1  notes=${notes.length} links=${notes.reduce((s, n) => s + n.links.length, 0)}`);
  L.push('# Generated by tools/vault. Do not edit. L1 of the retrieval protocol.');
  L.push('');
  if (CONFIG.stack.length) {
    L.push('## STACK');
    for (const line of CONFIG.stack) L.push(line);
    L.push('');
  }
  const invariants = invariantLines(notes);
  if (invariants.length) {
    L.push('## INVARIANTS (canon Architecture/Invariants.md, verbatim headings)');
    for (const line of invariants) L.push(line);
    L.push('');
  }

  const statusLines = [];
  if (steps.done.length) statusLines.push(`done  ${steps.done.join(' | ')}`);
  if (steps.next.length) statusLines.push(`next  ${steps.next.join(' | ')}`);
  if (steps.todo.length) statusLines.push(`todo  ${steps.todo.join(' | ')}`);
  if (steps.extra.length) statusLines.push(`extra ${steps.extra.join(' | ')}`);
  if (statusLines.length) {
    L.push('## STATUS (canon Roadmap & Status.md)');
    for (const line of statusLines) L.push(line);
    L.push('');
  }
  // Each block below is omitted when its adapter returned nothing. Under the
  // `none` adapter that is every one of them, which is what lets the vault run
  // on a stack this tooling does not understand yet — the alternative is a
  // header followed by a blank line, which reads as "there are no entities"
  // rather than "nobody looked".
  const hasTests = Boolean(tests.unit.files || tests.int.files);
  const codeLines = [];
  if (ctx.entities.length) codeLines.push(`entities    ${ctx.entities.map((e) => `${e.cls}->${e.table}`).join(' ')}`);
  if (ctx.migrations.length) codeLines.push(`migrations  ${ctx.migrations.map((m) => m.name).join(' ')}`);
  if (ctx.providers.length) codeLines.push(`providers   ${ctx.providers.map((p) => `${p.cls}(${p.source})`).join(' ')}`);
  if (hasTests) {
    codeLines.push(`tests       unit ${t.unit}`);
    codeLines.push(`            int  ${t.int}`);
  }
  if (codeLines.length) {
    L.push(`## CODE (derived from ${CODE_PREFIX}src)`);
    for (const line of codeLines) L.push(line);
    L.push('');
  }

  const withDefaults = sortBy([...env.defaults].filter(([, v]) => v !== ''), ([k]) => k);
  const optional = sortBy(env.used.filter((k) => !env.defaults.get(k)));
  if (withDefaults.length || optional.length || env.missing.length) {
    L.push(`## ENV (canon ${CODE_PREFIX}.env.example)`);
    if (withDefaults.length) L.push(withDefaults.map(([k, v]) => `${k}=${v}`).join(' '));
    if (optional.length) L.push(`optional ${optional.join(' ')}`);
    if (env.missing.length) L.push(`WARN used in code, undocumented in .env.example: ${env.missing.join(' ')}`);
    L.push('');
  }

  const cmds = AGENT_SCRIPTS.filter((s) => ctx.scripts.has(s)).map((s) => (s === 'lint' ? 'lint(WARNING: --fix, mutates)' : s));
  if (cmds.length) {
    L.push(`## CMDS (cd ${BACKEND_DIR})`);
    L.push(cmds.join(' | '));
    L.push('');
  }
  const dod = dodSection(notes);
  if (dod.length) {
    L.push('## DOD (canon Roadmap & Status.md#Definition of Done)');
    for (const line of dod) L.push(line);
    L.push('');
  }
  L.push('## RETRIEVAL');
  L.push('L2  node tools/vault/v.mjs find <query>    -> ranked path#N :: heading');
  L.push('L3  node tools/vault/v.mjs show <ref>      -> one section + exact Read offsets if truncated');
  L.push(`    refs accept ${CONFIG.exampleRef}`);
  L.push('L4  Read <path>  -- only when about to EDIT that note');
  // Only advertise the code map when something was actually indexed into it.
  if (ctx.codeMap.length) L.push(`code  Read ${GEN_DIR}/code-map.txt  -- before editing ${CODE_PREFIX}src, instead of grepping`);
  L.push('subagents: pass refs, never pasted note bodies; first call is `brief <ref>...`');
  if (graph.dangling.length) L.push(`WARN dangling links: ${graph.dangling.length}`);
  if (graph.unreachable.length) L.push(`WARN unreachable from 00 — Index: ${graph.unreachable.length} notes (see _gen/health.txt)`);

  return L.join('\n');
}

// ------------------------------------------------------------------ map.tsv

export function renderMap(ctx) {
  const rows = ['# path\ttype\tsummary'];
  for (const n of sortBy(ctx.notes, (n) => n.rel)) {
    const summary = (n.data?.summary || '').replace(/\t/g, ' ').trim();
    rows.push(`${n.rel}\t${n.type}\t${summary}`);
  }
  return rows.join('\n');
}

// --------------------------------------------------------------- index.json

export function renderIndex(ctx) {
  return JSON.stringify(
    {
      version: 1,
      notes: sortBy(ctx.notes, (n) => n.rel).map((n) => ({
        rel: n.rel,
        path: n.path,
        name: n.name,
        type: n.type,
        summary: n.data?.summary || null,
        rev: n.data?.rev || null,
        headings: n.headings
          .filter((h) => h.level >= 2)
          .map((h, i) => ({ n: i + 1, level: h.level, text: h.text, line: h.line, endLine: h.endLine })),
      })),
    },
    null,
    2,
  );
}

// --------------------------------------------------------------- graph.json

export function renderGraph(ctx) {
  const { graph } = ctx;
  return JSON.stringify(
    {
      version: 1,
      metrics: {
        notes: ctx.notes.length,
        linkOccurrences: ctx.notes.reduce((s, n) => s + n.links.length, 0),
        distinctTargets: new Set(ctx.notes.flatMap((n) => n.links.map((l) => l.target))).size,
        dangling: graph.dangling.length,
        caseMismatch: graph.caseMismatch.length,
        components: graph.components.length,
        orphans: graph.orphans.length,
        unreachableFromIndex: graph.unreachable.length,
      },
      nodes: graph.nodes,
      edges: graph.edges,
      components: graph.components,
      orphans: graph.orphans,
      unreachable: graph.unreachable,
      dangling: graph.dangling,
      caseMismatch: graph.caseMismatch,
    },
    null,
    2,
  );
}

// ------------------------------------------------------------ code-map.txt

/**
 * The code-side index. Deliberately NOT folded into context.txt: it is about
 * the same size as the whole L1 pack and only matters when an agent is about
 * to touch `backend/src`, so it stays a separate on-demand Read.
 */
export function renderCodeMap(ctx) {
  const L = [
    `# code-map v1  files=${ctx.codeMap.length}  symbols=${ctx.codeMap.reduce((s, f) => s + f.symbols.length, 0)}`,
    '# Generated by tools/vault from backend/src (specs excluded) + tools/vault. Do not edit.',
    '# Read this instead of grepping before you change backend or tooling code.',
  ];

  let currentDir = null;
  let currentScope = null;
  for (const f of ctx.codeMap) {
    // Compare on scope too: two scopes can both have a root group (dir === ''),
    // and keying only on `dir` would silently merge them under one heading.
    if (f.dir !== currentDir || f.scope !== currentScope) {
      currentDir = f.dir;
      currentScope = f.scope;
      L.push('');
      L.push(`## ${f.scope}/${currentDir || ''}`.replace(/\/$/, ''));
    }
    const syms = f.symbols.map((s) => `${s.kind} ${s.name}`).join(', ');
    // Explicit separator, not just padEnd: padEnd does not truncate, so a name
    // longer than the column (the timestamped migrations) would otherwise run
    // straight into its own symbol list.
    L.push(`${f.base.padEnd(33)} ${syms || '-'}`);
  }

  return L.join('\n');
}

// -------------------------------------------------------------- health.txt

export function renderHealth(ctx) {
  // `staged` is stripped deliberately: health.txt must be a pure function of the
  // worktree. Leaving it in makes the file's content depend on what happens to
  // be staged, so `check --staged` would report health.txt as stale purely
  // because a staged-only rule fired — a self-referential flap.
  const findings = collectFindings({ ...ctx, staged: null });
  const L = ['# vault health — generated, do not edit'];
  const bySeverity = { error: [], warn: [], info: [] };
  for (const f of findings) (bySeverity[f.severity] || bySeverity.info).push(f);

  L.push(`errors=${bySeverity.error.length} warnings=${bySeverity.warn.length}`);
  for (const sev of ['error', 'warn', 'info']) {
    const list = bySeverity[sev];
    if (!list.length) continue;
    L.push('');
    L.push(`## ${sev.toUpperCase()}`);
    for (const f of sortBy(list, (f) => `${f.rule}:${f.where || ''}`)) {
      L.push(`${f.rule}\t${f.where || '-'}\t${f.message}`);
    }
  }
  return L.join('\n');
}

// ------------------------------------------------------------- auto-blocks

const BLOCK_RE = (id) =>
  new RegExp(`(<!--\\s*auto:${id}\\s+begin\\s*-->)([\\s\\S]*?)(<!--\\s*auto:${id}\\s+end\\s*-->)`, 'g');

/** Replace the body of every `<!-- auto:<id> begin -->…end` block present in `text`. */
export function fillBlocks(text, blocks) {
  let out = text;
  for (const [id, body] of Object.entries(blocks)) {
    out = out.replace(BLOCK_RE(id), (_m, open, _old, close) => `${open}\n${body.replace(/\s+$/, '')}\n${close}`);
  }
  return out;
}

/** Bodies for every auto-block this repo knows how to generate. */
export function autoBlocks(ctx) {
  const t = testSummary(ctx.tests);
  return {
    migrations: ctx.migrations
      .map((m, i) => `${i + 1}. \`${m.ts}-${m.cls.replace(/\d+$/, '')}\`${m.tables.length ? ` — ${m.tables.map((x) => `\`${x}\``).join(', ')}` : ''}`)
      .join('\n'),
    entities: ctx.entities.map((e) => `- \`${e.cls}\` → \`${e.table}\` (${e.columns.length} колонок)`).join('\n'),
    providers: ctx.providers.map((p) => `- \`${p.cls}\` — \`source = '${p.source}'\``).join('\n'),
    tests: `unit ${t.unit}; int ${t.int}`,
    invariants: invariantLines(ctx.notes).map((l) => `- ${l}`).join('\n'),
    cmds: AGENT_SCRIPTS.filter((s) => ctx.scripts.has(s)).map((s) => `- \`npm run ${s}\``).join('\n'),
  };
}

// ------------------------------------------------------------------- build

const GEN_FILES = {
  'context.txt': renderContext,
  'code-map.txt': renderCodeMap,
  'map.tsv': renderMap,
  'index.json': renderIndex,
  'graph.json': renderGraph,
  'health.txt': renderHealth,
};

export function build(root, flags = {}) {
  if (flags['seed-frontmatter']) return seedFrontmatter(root);
  if (flags['seed-facts']) return seedFacts(root);
  if (flags['seed-rev']) return seedRev(root);

  const ctx = buildContext(root);
  const genDir = path.resolve(root, GEN_DIR);
  mkdirSync(genDir, { recursive: true });

  const changed = [];
  for (const [name, fn] of Object.entries(GEN_FILES)) {
    if (writeText(path.resolve(genDir, name), fn(ctx))) changed.push(`${GEN_DIR}/${name}`);
  }

  // Auto-blocks in hand-written notes (no-op until the markers are inserted).
  const blocks = autoBlocks(ctx);
  for (const note of ctx.notes) {
    const abs = path.resolve(root, note.path);
    const before = readText(abs);
    const after = fillBlocks(before, blocks);
    if (after !== before && writeText(abs, after)) changed.push(note.rel);
  }
  for (const extra of ['CLAUDE.md']) {
    const abs = path.resolve(root, extra);
    if (!exists(abs)) continue;
    const before = readText(abs);
    const after = fillBlocks(before, blocks);
    if (after !== before && writeText(abs, after)) changed.push(extra);
  }

  process.stdout.write(changed.length ? `vault build: updated ${changed.length}\n${sortBy(changed).join('\n')}\n` : 'vault build: up to date\n');
  return 0;
}

// ------------------------------------------------------------- seed helpers

/**
 * Propose a `summary:` for every note from its existing opening abstract.
 * Prints a review list rather than editing 25 notes, so the human/LLM edits a
 * 25-line proposal instead of reading the whole vault (~35k tokens -> ~1.5k).
 */
export function seedFrontmatter(root) {
  const notes = loadNotes(root);
  const out = ['# proposed summaries — review, then paste into each note as frontmatter', '# rel\tsummary'];
  for (const n of sortBy(notes, (x) => x.rel)) {
    if (n.data?.summary) { out.push(`${n.rel}\t${n.data.summary}\t(existing)`); continue; }
    const abstract = firstParagraph(n);
    out.push(`${n.rel}\t${abstract}`);
  }
  process.stdout.write(out.join('\n') + '\n');
  return 0;
}

function firstParagraph(note) {
  const buf = [];
  for (let i = note.bodyStartLine - 1; i < note.lines.length; i++) {
    const line = note.lines[i].trim();
    if (/^#/.test(line)) { if (buf.length) break; continue; }
    if (/^>/.test(line) || /^```/.test(line)) { if (buf.length) break; continue; }
    if (!line) { if (buf.length) break; continue; }
    buf.push(line);
    if (buf.join(' ').length > 110) break;
  }
  return buf
    .join(' ')
    .replace(/!?\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|([^\]]*))?\]\]/g, (_, t, a) => a || t)
    .replace(/\*\*/g, '')
    .replace(/\s+/g, ' ')
    .slice(0, 120)
    .trim();
}

/** Propose fact keys: normalized >=6-word n-grams appearing in >=3 notes. */
export function seedFacts(root) {
  const notes = loadNotes(root);
  const seen = new Map(); // ngram -> Set(note.rel)
  for (const n of notes) {
    const words = norm(n.body)
      .toLocaleLowerCase('uk')
      .replace(/!?\[\[[^\]]*\]\]/g, ' ')
      .split(/[^\p{L}\p{N}_(),.]+/u)
      .filter(Boolean);
    for (let i = 0; i + 6 <= words.length; i++) {
      const gram = words.slice(i, i + 6).join(' ');
      if (gram.length < 25) continue;
      if (!seen.has(gram)) seen.set(gram, new Set());
      seen.get(gram).add(n.rel);
    }
  }
  const rows = [...seen.entries()].filter(([, s]) => s.size >= 3).sort((a, b) => b[1].size - a[1].size || cmp(a[0], b[0]));
  const out = ['# candidate duplicated facts — pick an owner for each', '# notes\tngram\tappears_in'];
  for (const [gram, set] of rows.slice(0, 40)) out.push(`${set.size}\t${gram}\t${sortBy([...set]).join(' | ')}`);
  process.stdout.write(out.join('\n') + '\n');
  return 0;
}

/**
 * One-time bootstrap: fill `rev:` on notes that have a `code:` glob but no pin.
 *
 * The `rev-stale` rule needs a baseline to compare against, so until every
 * `code:` note carries a digest the whole staleness gate is inert. This exists
 * ONLY to establish that baseline: it never touches a note that already has a
 * pin, so the "you cannot pin a note you did not edit" guarantee enforced by
 * `pin()` below stays intact for every subsequent change. Re-running it after
 * the bootstrap is a no-op.
 */
export function seedRev(root) {
  const notes = loadNotes(root);
  const pinned = [];

  for (const note of notes) {
    if (!note.data?.code?.length || note.data.rev) continue;
    const files = expandPatterns(root, note.data.code.map(resolveCodePattern));
    const rev = digestFiles(root, files);
    const abs = path.resolve(root, note.path);
    const cur = fmParse(readText(abs));
    writeText(abs, fmSerialize({ ...cur.data, rev }, cur.body));
    pinned.push(`${note.rel}\t${rev}\t${files.length} files`);
  }

  process.stdout.write(
    pinned.length
      ? `vault build --seed-rev: pinned ${pinned.length}\n${sortBy(pinned).join('\n')}\n`
      : 'vault build --seed-rev: every code: note already pinned\n',
  );
  return 0;
}

// ------------------------------------------------------------------ decide

/**
 * Append a row to the Decision Log. WRITES — never callable from a hook.
 *
 * The `check` rules already require a Decision Log row for every architectural
 * choice, but nothing made writing one CHEAP, so rows did not get written
 * mid-task. This is deliberately a one-call operation.
 *
 * Use it for REJECTED approaches too, not only adopted ones: "what a previous
 * agent tried and discarded" is the knowledge most often re-derived from
 * scratch, and it has no other home in the vault.
 *
 * Section resolution mirrors `resolveRef`'s precedence (exact -> normalized ->
 * positional -> substring -> ambiguous prints the list), so the same mental
 * model works everywhere and no Ukrainian has to be typed into a shell.
 */
export function decide(root, text, flags = {}) {
  const rel = 'Decisions/Decision Log.md';
  const notes = loadNotes(root);
  const note = notes.find((n) => n.rel === rel);
  if (!note) {
    process.stderr.write(`vault decide: ${rel} not found\n`);
    return 2;
  }

  const sections = note.headings.map((h, i) => ({ h, i })).filter(({ h }) => h.level === 2);
  const listSections = () =>
    sections.map(({ h }, n) => `  #${n + 1} ${h.text}`).join('\n') + '\n';

  const spec = typeof flags.section === 'string' ? flags.section.trim() : '';
  if (!spec) {
    process.stderr.write(`vault decide: --section required. Sections of ${rel}:\n${listSections()}`);
    return 2;
  }

  const normalize = (s) => norm(s).replace(/\s+/g, ' ').trim().toLocaleLowerCase('uk');
  let hit = sections.filter(({ h }) => h.text === spec);
  if (hit.length !== 1) hit = sections.filter(({ h }) => normalize(h.text) === normalize(spec));
  if (hit.length !== 1 && /^\d+$/.test(spec)) {
    const idx = Number(spec) - 1;
    hit = idx >= 0 && idx < sections.length ? [sections[idx]] : [];
  }
  if (hit.length !== 1) hit = sections.filter(({ h }) => normalize(h.text).includes(normalize(spec)));

  if (hit.length !== 1) {
    process.stderr.write(
      `vault decide: ${hit.length ? 'ambiguous' : 'no'} section '${spec}'. Sections of ${rel}:\n${listSections()}`,
    );
    return 2;
  }

  // Keep the file's established shape rather than inventing one.
  const line = /^\s*-\s/.test(text) ? text.replace(/^\s*/, '') : `- ${text}`;

  // Insert after the last non-blank line of the section, so a trailing blank
  // line before the next heading is preserved.
  const { h } = hit[0];
  const lines = [...note.lines];
  let at = h.endLine;
  while (at > h.line && !lines[at - 1].trim()) at--;
  lines.splice(at, 0, line);

  writeText(path.resolve(root, note.path), lines.join('\n'));
  process.stdout.write(`vault decide: ${rel} :: ${h.text}\n  ${line}\nRun \`vault check\` — the new line is subject to status-leak and fact-restated like any other prose.\n`);
  return 0;
}

// --------------------------------------------------------------------- pin

/**
 * Re-pin a note's `rev:` digest. Refuses unless the note has a staged
 * non-`rev` diff — you cannot acknowledge a change to a note you did not edit.
 */
export function pin(root, noteSpec) {
  const notes = loadNotes(root);
  const note = notes.find((n) => n.rel === noteSpec || n.path === noteSpec || n.name === noteSpec);
  if (!note) { process.stderr.write(`vault pin: no note '${noteSpec}'\n`); return 2; }
  if (!note.data?.code?.length) { process.stderr.write(`vault pin: '${note.rel}' has no code: field, nothing to pin\n`); return 2; }

  const staged = stagedPaths();
  if (!staged.includes(note.path)) {
    process.stderr.write(`vault pin: refusing — '${note.rel}' has no staged edit.\n  You cannot pin a note you did not change. Edit it, git add it, then pin.\n`);
    return 1;
  }
  const stagedText = git(['show', `:${note.path}`], { raw: true });
  const head = fmParse(norm(stagedText));
  const cur = fmParse(readText(path.resolve(root, note.path)));
  if (JSON.stringify({ ...head.data, rev: null }) === JSON.stringify({ ...cur.data, rev: null }) && head.body === cur.body) {
    // staged content identical apart from rev -> the only staged change IS the pin
    process.stderr.write(`vault pin: refusing — '${note.rel}' staged diff is the rev: pin only.\n`);
    return 1;
  }

  const files = expandPatterns(root, note.data.code.map(resolveCodePattern));
  const rev = digestFiles(root, files);
  const next = fmSerialize({ ...cur.data, rev }, cur.body);
  writeText(path.resolve(root, note.path), next);
  process.stdout.write(`vault pin: ${note.rel} rev=${rev} (${files.length} files)\n`);
  return 0;
}

export { GEN_FILES };
