/**
 * Generated vault artifacts. `build()` is intentionally the only mutating
 * path for curated derived output; check/retrieval stay hook-safe. The separate
 * explicitly invoked evidence runner may write only its ignored local cache.
 */
import { mkdirSync } from 'node:fs';
import * as path from 'node:path';
import { collectCodeFacts } from './code.mjs';
import { readTextOrNull, sortBy, writeGeneratedText } from './fs.mjs';
import { buildGraph, resolveNoteReference } from './graph.mjs';
import { loadNotes } from './notes.mjs';

export async function buildContext(root, config) {
  const notes = loadNotes(root, config);
  const graph = buildGraph(notes, config);
  const code = await collectCodeFacts(root, config);
  return { root, config, notes, graph, ...code };
}

function roadmapSummary(notes, config) {
  const resolved = resolveNoteReference(notes, config.roadmapNote);
  if (!resolved?.note) return null;
  const note = resolved.note;
  let done = 0;
  let open = 0;
  for (const line of note.lines) {
    const checkbox = line.match(/^\s*-\s*\[([ xX])\]/);
    if (!checkbox) continue;
    if (checkbox[1].toLowerCase() === 'x') done++;
    else open++;
  }
  return { note, done, open };
}

export function renderContext(ctx) {
  const {
    config,
    notes,
    graph,
    entities = [],
    migrations = [],
    providers = [],
    env,
    scripts,
    tests,
  } = ctx;
  const lines = [
    `# vault context v1  notes=${notes.length} links=${graph.edges.length}`,
    '# Generated by tools/vault. Do not edit; rebuild with `vault build`.',
    '',
    '## ROUTES',
    `index    ${config.indexNote}`,
    `roadmap  ${config.roadmapNote}`,
    `context  ${config.vaultDir}/${config.contextDir}/ (background only; excluded from graph and search)`,
  ];
  if (config.currentContext)
    lines.push(
      `handoff  ${config.vaultDir}/${config.currentContext} (read separately; excluded from graph and search)`,
    );

  if (config.stack.length) {
    lines.push('', '## STACK');
    lines.push(...config.stack);
  }

  const roadmap = roadmapSummary(notes, config);
  if (roadmap) {
    lines.push(
      '',
      `## STATUS (canon ${roadmap.note.rel})`,
      `checkboxes  done=${roadmap.done} open=${roadmap.open}`,
    );
  } else {
    lines.push('', `## STATUS`, `roadmap note '${config.roadmapNote}' is not present yet`);
  }

  // Adapters may return no facts (`none` does), which means no source surface
  // was inspected.  Omit this block rather than implying the project has no
  // entities, migrations, providers, or tests.
  const code = [];
  if (entities.length) code.push(`entities    ${entities.length}`);
  if (migrations.length) code.push(`migrations  ${migrations.length}`);
  if (providers.length)
    code.push(
      `providers   ${providers
        .map((provider) => `${provider.cls}${provider.source ? `(${provider.source})` : ''}`)
        .join(' ')}`,
    );
  if (tests?.unit?.files || tests?.int?.files) {
    code.push(`tests       unit ${tests.unit.cases}/${tests.unit.files} files`);
    code.push(`            integration ${tests.int.cases}/${tests.int.files} files`);
  }
  if (code.length) {
    lines.push('', `## CODE (derived from ${config.codeRoot})`, ...code);
    if (ctx.codeMap?.length)
      lines.push(`map         ${config.vaultDir}/_gen/code-map.txt (read before source edits)`);
    lines.push(`facts       ${config.vaultDir}/_gen/facts.txt (verified adapter facts)`);
  }

  if (env?.used?.length || env?.documented?.length || env?.missing?.length) {
    lines.push('', '## ENVIRONMENT');
    lines.push(`used=${env.used.length} documented=${env.documented.length}`);
    if (env.missing.length)
      lines.push(`WARN code variables missing from .env.example: ${env.missing.join(' ')}`);
  }

  const runnable = (config.agentScripts || []).filter((name) => scripts?.has(name));
  if (runnable.length) {
    lines.push('', '## QUALITY COMMANDS', ...runnable.map((name) => `npm run ${name}`));
  }

  lines.push(
    '',
    '## RETRIEVAL',
    'L2  node tools/vault/v.mjs find <query>  -> ranked note or section references',
    'L3  node tools/vault/v.mjs show <ref>    -> one note section',
    `    refs accept ${config.exampleRef}`,
    'L4  Read <path> only when about to edit that file',
    'subagents: pass refs, not pasted note bodies; begin with `vault brief <ref>...`',
  );

  if (graph.dangling.length) lines.push(`WARN dangling curated links: ${graph.dangling.length}`);
  if (graph.ambiguous.length) lines.push(`WARN ambiguous curated links: ${graph.ambiguous.length}`);
  if (!graph.index) lines.push(`WARN configured index '${config.indexNote}' does not resolve`);
  return lines.join('\n');
}

export function renderMap(ctx) {
  const rows = ['# path\ttitle\ttype\tsummary'];
  for (const note of sortBy(ctx.notes, (item) => item.rel)) {
    const clean = (value) =>
      String(value || '')
        .replace(/[\t\r\n]+/g, ' ')
        .trim();
    rows.push(
      `${note.rel}\t${clean(note.title)}\t${clean(note.type)}\t${clean(note.data.summary)}`,
    );
  }
  return rows.join('\n');
}

export function renderIndex(ctx) {
  return JSON.stringify(
    {
      version: 1,
      indexNote: ctx.graph.index,
      contextExcluded: `${ctx.config.vaultDir}/${ctx.config.contextDir}`,
      notes: sortBy(ctx.notes, (note) => note.rel).map((note) => ({
        rel: note.rel,
        path: note.path,
        name: note.name,
        title: note.title,
        type: note.type,
        summary: note.data.summary || null,
        rev: note.data.rev || null,
        headings: note.headings
          .filter((heading) => heading.level >= 2)
          .map((heading, index) => ({
            n: index + 1,
            level: heading.level,
            text: heading.text,
            line: heading.line,
            endLine: heading.endLine,
          })),
      })),
    },
    null,
    2,
  );
}

export function renderGraph(ctx) {
  const { graph, notes } = ctx;
  return JSON.stringify(
    {
      version: 1,
      metrics: {
        notes: notes.length,
        links: graph.edges.length,
        dangling: graph.dangling.length,
        ambiguous: graph.ambiguous.length,
        caseMismatch: graph.caseMismatch.length,
        components: graph.components.length,
        orphans: graph.orphans.length,
        unreachableFromIndex: graph.unreachable.length,
      },
      ...graph,
    },
    null,
    2,
  );
}

export function renderCodeMap(ctx) {
  const rows = ctx.codeMap || [];
  const lines = [
    `# code-map v1  files=${rows.length} symbols=${rows.reduce((total, row) => total + (row.symbols?.length || 0), 0)}`,
    '# Generated by the configured vault adapter. Do not edit.',
  ];
  if (!rows.length) {
    lines.push(`# No code map: adapter '${ctx.config.adapter}' supplied no code surface.`);
    return lines.join('\n');
  }
  let currentScope = null;
  let currentDirectory = null;
  for (const row of sortBy(
    rows,
    (item) => `${item.scope || ''}\0${item.dir || ''}\0${item.base || item.file || ''}`,
  )) {
    if (row.scope !== currentScope || row.dir !== currentDirectory) {
      currentScope = row.scope;
      currentDirectory = row.dir;
      lines.push('', `## ${[row.scope, row.dir].filter(Boolean).join('/') || 'code'}`);
    }
    const symbols = (row.symbols || [])
      .map((symbol) => `${symbol.kind || 'symbol'} ${symbol.name}`)
      .join(', ');
    lines.push(`${row.base || row.file}\t${symbols || '-'}`);
  }
  return lines.join('\n');
}

/**
 * Adapter facts stay separate from the symbol map: the former answers "what
 * data/configuration surface exists?", while the latter answers "where do I
 * edit?".  Both are generated from explicit source files and never guessed.
 */
export function renderFacts(ctx) {
  const { config, entities = [], migrations = [], providers = [], env, scripts, tests } = ctx;
  const lines = [
    '# vault source facts v1',
    '# Generated by the configured adapter. Do not edit; rebuild with `vault build`.',
    `adapter=${config.adapter}`,
  ];

  if (entities.length) {
    lines.push('', '## ENTITIES');
    for (const entity of sortBy(entities, (item) => item.table || item.cls)) {
      const columns = entity.columns?.length ? ` columns=${entity.columns.length}` : '';
      lines.push(`${entity.cls}\t${entity.table || '-'}\t${entity.file || '-'}${columns}`);
    }
  }
  if (migrations.length) {
    lines.push('', '## MIGRATIONS');
    for (const migration of sortBy(migrations, (item) => `${item.ts || ''}\0${item.file || ''}`)) {
      const tables = migration.tables?.length ? migration.tables.join(', ') : '-';
      lines.push(`${migration.name || migration.file}\t${tables}`);
    }
  }
  if (providers.length) {
    lines.push('', '## PROVIDERS');
    for (const provider of sortBy(providers, (item) => `${item.file || ''}\0${item.cls || ''}`)) {
      lines.push(`${provider.cls}\t${provider.source || '-'}\t${provider.file || '-'}`);
    }
  }
  if (env?.used?.length || env?.documented?.length || env?.missing?.length) {
    lines.push('', '## ENVIRONMENT');
    if (env.used?.length) lines.push(`used\t${sortBy(env.used).join(' ')}`);
    if (env.documented?.length) lines.push(`documented\t${sortBy(env.documented).join(' ')}`);
    if (env.missing?.length) lines.push(`undocumented\t${sortBy(env.missing).join(' ')}`);
  }
  if (scripts?.size) {
    lines.push('', '## NPM SCRIPTS');
    for (const [name, command] of sortBy([...scripts], ([name]) => name))
      lines.push(`${name}\t${command}`);
  }
  if (tests?.unit || tests?.int) {
    lines.push('', '## TEST COUNTS');
    for (const [kind, side] of [
      ['unit', tests.unit],
      ['integration', tests.int],
    ]) {
      if (side?.files) lines.push(`${kind}\tcases=${side.cases} files=${side.files}`);
    }
    if (tests.only?.length) lines.push(`focused\t${tests.only.join(' ')}`);
  }

  if (lines.length === 3) lines.push('', '# The selected adapter returned no source facts.');
  return lines.join('\n');
}

export function renderHealth(ctx) {
  const { graph } = ctx;
  const lines = [
    '# vault graph health — generated, do not edit',
    '# For frontmatter, source-fact, retrieval, and freshness findings run `vault check`.',
    `notes=${ctx.notes.length} links=${graph.edges.length} components=${graph.components.length}`,
    `dangling=${graph.dangling.length} ambiguous=${graph.ambiguous.length} case_mismatch=${graph.caseMismatch.length}`,
    `orphans=${graph.orphans.length} unreachable=${graph.unreachable.length}`,
  ];
  const sections = [
    ['DANGLING', graph.dangling.map((item) => `${item.from}:${item.line}\t[[${item.target}]]`)],
    [
      'AMBIGUOUS',
      graph.ambiguous.map(
        (item) => `${item.from}:${item.line}\t[[${item.target}]] -> ${item.candidates.join(' | ')}`,
      ),
    ],
    [
      'CASE MISMATCH',
      graph.caseMismatch.map(
        (item) => `${item.from}:${item.line}\t${item.target} -> ${item.actual}`,
      ),
    ],
    ['UNREACHABLE', graph.unreachable],
  ];
  for (const [title, entries] of sections) {
    if (!entries.length) continue;
    lines.push('', `## ${title}`, ...entries);
  }
  return lines.join('\n');
}

export const GEN_RENDERERS = Object.freeze({
  'context.txt': renderContext,
  'map.tsv': renderMap,
  'index.json': renderIndex,
  'graph.json': renderGraph,
  'code-map.txt': renderCodeMap,
  'facts.txt': renderFacts,
  'health.txt': renderHealth,
});

export function renderGenerated(ctx) {
  return Object.fromEntries(
    Object.entries(GEN_RENDERERS).map(([name, renderer]) => [name, renderer(ctx)]),
  );
}

/** The engine's only writer. It only changes the configured vault's `_gen/` directory. */
export async function build(root, config) {
  const ctx = await buildContext(root, config);
  const outputDirectory = path.resolve(root, config.vaultDir, '_gen');
  mkdirSync(outputDirectory, { recursive: true });
  const changed = [];
  for (const [name, content] of Object.entries(renderGenerated(ctx))) {
    const output = path.resolve(outputDirectory, name);
    if (writeGeneratedText(output, content)) changed.push(`${config.vaultDir}/_gen/${name}`);
  }
  process.stdout.write(
    changed.length
      ? `vault build: updated ${changed.length}\n${sortBy(changed).join('\n')}\n`
      : 'vault build: up to date\n',
  );
  return 0;
}

export function generatedFile(root, config, name) {
  return readTextOrNull(path.resolve(root, config.vaultDir, '_gen', name));
}
